"""Pydantic schemas for the DepScreen DSM-5 screening platform."""

from datetime import datetime

from pydantic import BaseModel, Field

# ── Symptom Detection Schemas ─────────────────────────────────────────────────


class SymptomDetection(BaseModel):
    """A single DSM-5 symptom detected in a sentence."""

    symptom: str = Field(description="Symptom code, e.g. 'DEPRESSED_MOOD'")
    symptom_label: str = Field(description="Human-readable label, e.g. 'Depressed Mood'")
    status: int = Field(description="1 = symptom present, 0 = explicitly absent")
    confidence: float = Field(ge=0.0, le=1.0, description="Model confidence for this prediction")
    sentence_text: str = Field(description="The sentence that triggered this detection")
    sentence_id: str | None = Field(default=None, description="Sentence identifier for reference")


class PostSymptomSummary(BaseModel):
    """Aggregated symptom analysis for a complete text submission."""

    symptoms_detected: list[SymptomDetection] = Field(
        default_factory=list, description="All detected symptoms with sentence-level evidence"
    )
    unique_symptom_count: int = Field(description="Count of distinct DSM-5 symptoms detected")
    total_sentences_analyzed: int = Field(description="Total sentences the text was split into")
    severity_level: str = Field(description="Severity: 'none', 'mild', 'moderate', or 'severe'")
    severity_explanation: str = Field(description="Clinical context for the severity level")
    dsm5_criteria_met: list[str] = Field(default_factory=list, description="Which of the 9 DSM-5 criteria are met")


# ── LLM Verification Schemas ─────────────────────────────────────────────────


class EvidenceValidation(BaseModel):
    """LLM validation of whether detected symptoms are genuinely supported."""

    evidence_supports_prediction: bool = Field(
        description="Whether the sentence evidence supports the symptom detections"
    )
    coherence_score: float = Field(ge=0.0, le=1.0, description="How well the evidence fits the predictions (0-1)")
    alternative_interpretation: str | None = Field(
        default=None, description="Alternative interpretation if evidence seems contradictory"
    )
    flagged_for_review: bool = Field(default=False, description="Whether this case should be flagged for human review")


class ConfidenceAnalysis(BaseModel):
    """LLM meta-analysis of overall screening reliability."""

    should_trust_prediction: str = Field(description="Trust level: 'high', 'medium', or 'low'")
    reasoning: str = Field(description="Explanation for the trust assessment")
    potential_confounders: list[str] = Field(
        default_factory=list, description="Factors that might affect screening accuracy (sarcasm, metaphor, etc.)"
    )
    recommended_threshold_adjustment: float | None = Field(
        default=None, description="Suggested confidence adjustment multiplier"
    )


class AdversarialCheck(BaseModel):
    """LLM detection of potentially adversarial or unusual inputs."""

    likely_adversarial: bool = Field(default=False, description="Whether the input appears to be gaming the system")
    adversarial_type: str | None = Field(
        default=None, description="Type: 'prompt_injection', 'copypasta', 'gibberish', 'keyword_stuffing'"
    )
    authenticity_score: float = Field(ge=0.0, le=1.0, description="How genuine the input seems (0-1)")
    warning: str | None = Field(default=None, description="Warning message if adversarial patterns detected")


class VerificationReport(BaseModel):
    """Combined LLM verification results."""

    evidence_validation: EvidenceValidation
    confidence_analysis: ConfidenceAnalysis
    adversarial_check: AdversarialCheck


# ── Explanation Schemas ───────────────────────────────────────────────────────


class ExplanationReport(BaseModel):
    """Human-readable explanation generated by LLM, enriched with RAG context."""

    summary: str = Field(description="Brief summary of the screening result")
    risk_level: str = Field(description="Severity level: 'none', 'mild', 'moderate', or 'severe'")
    symptom_explanations: dict[str, str] = Field(
        default_factory=dict,
        description="Per-symptom clinical context, e.g. {'SLEEP_ISSUES': 'Sleep disturbance is...'}",
    )
    why_model_thinks_this: str = Field(description="Explanation of what patterns led to these detections")
    key_evidence_quotes: list[str] = Field(
        default_factory=list, description="Key sentences from the input that triggered symptom detections"
    )
    uncertainty_notes: str = Field(description="Notes about screening uncertainty and limitations")
    safety_disclaimer: str = Field(description="Important safety and ethical disclaimer")
    resources: list[str] = Field(default_factory=list, description="Mental health resources and crisis hotlines")


# ── Evidence Schema ───────────────────────────────────────────────────────────


class Evidence(BaseModel):
    """Sentence-level evidence from the symptom classifier."""

    sentence_evidence: list[SymptomDetection] = Field(
        default_factory=list, description="All sentence-level symptom detections"
    )
    top_evidence_sentences: list[str] = Field(
        default_factory=list, description="Most important sentences (highest confidence detections)"
    )


# ── Request / Response Schemas ────────────────────────────────────────────────


class ScreeningRequest(BaseModel):
    """Request schema for screening endpoint."""

    text: str = Field(min_length=1, max_length=10000, description="Free-text input to screen for DSM-5 symptoms")


class ScreeningResponse(BaseModel):
    """Complete screening response with symptom analysis."""

    id: str = Field(description="Unique screening ID")
    created_at: datetime = Field(description="Timestamp of screening")

    # Input
    text: str = Field(description="Original input text")

    # Symptom analysis (core output)
    symptom_analysis: PostSymptomSummary = Field(
        description="Sentence-level symptom detections aggregated to post level"
    )

    # Evidence
    evidence: Evidence = Field(description="Sentence-level evidence")

    # LLM verification
    verification: VerificationReport = Field(description="LLM verification results")

    # Final assessment
    final_prediction: str = Field(
        description="Final assessment: 'no_indicators', 'some_indicators', 'significant_indicators'"
    )
    final_confidence: float = Field(ge=0.0, le=1.0, description="Final confidence after verification adjustments")
    confidence_adjusted: bool = Field(default=False, description="Whether LLM verification adjusted the confidence")

    # Human-readable output
    explanation_report: ExplanationReport = Field(
        description="LLM-generated explanation with RAG-enriched clinical context"
    )

    # Flags
    flagged_for_review: bool = Field(default=False, description="Whether flagged for clinician review")
    adversarial_warning: str | None = Field(default=None, description="Warning if adversarial input detected")


class ScreeningListItem(BaseModel):
    """Summary item for screening history list."""

    id: str
    created_at: datetime
    text_preview: str = Field(description="First 100 chars of input text")
    final_prediction: str
    final_confidence: float
    symptom_count: int = Field(description="Number of distinct symptoms detected")
    severity_level: str
    flagged_for_review: bool


class ScreeningHistoryResponse(BaseModel):
    """Paginated response for screening history."""

    items: list[ScreeningListItem]
    total: int
    page: int
    page_size: int


# ── Chat Schemas ──────────────────────────────────────────────────────────────


class ChatMessageRequest(BaseModel):
    """Request to send a chat message."""

    message: str = Field(min_length=1, max_length=2000, description="User message")


class ChatMessageResponse(BaseModel):
    """Single chat message."""

    id: str
    role: str = Field(description="'user' or 'assistant'")
    content: str
    created_at: datetime


class ChatHistoryResponse(BaseModel):
    """Full chat history for a screening."""

    screening_id: str
    messages: list[ChatMessageResponse]


# ── Auth Schemas ──────────────────────────────────────────────────────────────


class RegisterRequest(BaseModel):
    """User registration request."""

    email: str = Field(min_length=5, max_length=255)
    password: str = Field(min_length=8, max_length=128)
    full_name: str = Field(min_length=1, max_length=255)
    role: str = Field(description="'patient' or 'clinician'")
    clinician_code: str | None = Field(
        default=None, description="Clinician invite code (for patients linking to a clinician)"
    )


class LoginRequest(BaseModel):
    """Login request."""

    email: str
    password: str


class UserProfile(BaseModel):
    """Public user profile (no password hash)."""

    id: str
    email: str
    full_name: str
    role: str
    clinician_code: str | None = None
    created_at: datetime
    onboarding_completed: bool = False
    profile_picture_url: str | None = None
    language_preference: str | None = None
    reddit_username: str | None = None
    twitter_username: str | None = None
    # Demographics (used to pre-fill onboarding form for returning users)
    date_of_birth: str | None = None
    gender: str | None = None
    nationality: str | None = None
    cpr_number: str | None = None
    phone: str | None = None
    blood_type: str | None = None
    timezone: str | None = None


class TokenResponse(BaseModel):
    """JWT token response.

    refresh_token is delivered via httpOnly cookie, not in the JSON body.
    """

    access_token: str
    token_type: str = "bearer"
    user: UserProfile


class RefreshRequest(BaseModel):
    """Token refresh request."""

    refresh_token: str


# ── Dashboard Schemas ─────────────────────────────────────────────────────────


class DashboardStats(BaseModel):
    """Aggregate statistics for clinician dashboard."""

    total_patients: int
    total_screenings: int
    flagged_count: int
    severity_distribution: dict[str, int] = Field(description="Count per severity level: {'none': X, 'mild': Y, ...}")
    screenings_this_week: int


class PatientSummary(BaseModel):
    """Patient summary for clinician dashboard."""

    id: str
    full_name: str
    email: str
    date_of_birth: str | None = None
    gender: str | None = None
    cpr_number: str | None = None
    profile_picture_url: str | None = None
    last_screening_date: datetime | None = None
    last_severity: str | None = None
    last_symptom_count: int | None = None
    total_screenings: int


# ── Medication Schemas ────────────────────────────────────────────────────────


class MedicationCreate(BaseModel):
    name: str = Field(min_length=1, max_length=255)
    dosage: str | None = Field(None, max_length=100)
    frequency: str | None = Field(None, description="daily, twice_daily, weekly, as_needed")
    start_date: str | None = None
    end_date: str | None = None
    prescribed_by: str | None = None
    notes: str | None = None


class MedicationResponse(BaseModel):
    id: str
    name: str
    dosage: str | None = None
    frequency: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    prescribed_by: str | None = None
    notes: str | None = None
    is_active: bool
    created_at: datetime


# ── Allergy Schemas ───────────────────────────────────────────────────────────


class AllergyCreate(BaseModel):
    allergen: str = Field(min_length=1, max_length=255)
    allergy_type: str | None = Field(None, description="medication, food, environmental, other")
    severity: str | None = Field(None, description="mild, moderate, severe, life_threatening")
    reaction: str | None = None
    diagnosed_date: str | None = None
    notes: str | None = None


class AllergyResponse(BaseModel):
    id: str
    allergen: str
    allergy_type: str | None = None
    severity: str | None = None
    reaction: str | None = None
    diagnosed_date: str | None = None
    notes: str | None = None
    created_at: datetime


# ── Diagnosis Schemas ─────────────────────────────────────────────────────────


class DiagnosisCreate(BaseModel):
    condition: str = Field(min_length=1, max_length=255)
    icd10_code: str | None = Field(None, max_length=20)
    diagnosed_date: str | None = None
    status: str = Field(default="active", description="active, remission, resolved")
    diagnosed_by: str | None = None
    notes: str | None = None


class DiagnosisResponse(BaseModel):
    id: str
    condition: str
    icd10_code: str | None = None
    diagnosed_date: str | None = None
    status: str
    diagnosed_by: str | None = None
    notes: str | None = None
    created_at: datetime


# ── Screening Schedule Schemas ────────────────────────────────────────────────


class ScreeningScheduleCreate(BaseModel):
    frequency: str = Field(description="weekly, biweekly, monthly, custom")
    custom_days: int | None = None
    day_of_week: int | None = Field(None, ge=0, le=6, description="0=Monday, 6=Sunday")
    preferred_time: str | None = Field(None, description="HH:MM format")


class ScreeningScheduleResponse(BaseModel):
    id: str
    frequency: str
    custom_days: int | None = None
    day_of_week: int | None = None
    preferred_time: str | None = None
    next_due_at: datetime | None = None
    last_completed_at: datetime | None = None
    is_active: bool
    assigned_by: str | None = None
    assigned_by_name: str | None = None
    created_at: datetime


# ── Appointment Schemas ───────────────────────────────────────────────────────


class AppointmentCreate(BaseModel):
    patient_id: str
    scheduled_at: str  # ISO datetime
    duration_minutes: int = Field(default=60, ge=15, le=480)
    appointment_type: str = Field(default="followup", description="intake, followup, crisis, review")
    notes: str | None = None
    location: str | None = None


class AppointmentResponse(BaseModel):
    id: str
    patient_id: str
    clinician_id: str
    patient_name: str | None = None
    clinician_name: str | None = None
    scheduled_at: datetime
    duration_minutes: int
    appointment_type: str
    status: str
    notes: str | None = None
    location: str | None = None
    created_at: datetime


class AppointmentStatusUpdate(BaseModel):
    status: str = Field(description="scheduled, confirmed, completed, cancelled, no_show")


# ── Notification Schemas ──────────────────────────────────────────────────────


class NotificationResponse(BaseModel):
    id: str
    notification_type: str
    title: str
    message: str
    link: str | None = None
    is_read: bool
    created_at: datetime


# ── Care Plan Schemas ─────────────────────────────────────────────────────────


class CarePlanGoal(BaseModel):
    text: str
    target_date: str | None = None
    status: str = "in_progress"  # in_progress, achieved, revised


class CarePlanIntervention(BaseModel):
    name: str
    frequency: str | None = None
    instructions: str | None = None
    assigned_date: str | None = None


class CarePlanCreate(BaseModel):
    patient_id: str
    title: str = Field(min_length=1, max_length=255)
    description: str | None = None
    template_name: str | None = None
    goals: list[CarePlanGoal] = Field(default_factory=list)
    interventions: list[CarePlanIntervention] = Field(default_factory=list)
    review_date: str | None = None


class CarePlanResponse(BaseModel):
    id: str
    patient_id: str
    clinician_id: str
    patient_name: str | None = None
    clinician_name: str | None = None
    title: str
    description: str | None = None
    template_name: str | None = None
    goals: list[dict] = Field(default_factory=list)
    interventions: list[dict] = Field(default_factory=list)
    review_date: str | None = None
    status: str
    created_at: datetime
    updated_at: datetime


# ── Conversation Schemas ──────────────────────────────────────────────────────


class ConversationCreate(BaseModel):
    title: str | None = "New Conversation"
    context_type: str = Field(default="general", description="general, screening_followup, clinician_direct")
    linked_screening_id: str | None = None
    linked_clinician_id: str | None = None


class ConversationResponse(BaseModel):
    id: str
    title: str
    context_type: str
    linked_screening_id: str | None = None
    is_active: bool
    created_at: datetime
    updated_at: datetime
    message_count: int = 0


# ── Direct messaging (patient ↔ clinician) ──────────────────────────────────


class DirectMessageCreate(BaseModel):
    content: str = Field(min_length=1, max_length=5000)


class DirectMessageResponse(BaseModel):
    id: str
    role: str  # "user" (patient) or "clinician"
    sender_name: str | None = None
    content: str
    created_at: datetime


class DirectMessageThread(BaseModel):
    conversation_id: str
    patient_id: str
    patient_name: str
    clinician_id: str | None = None
    clinician_name: str | None = None
    messages: list[DirectMessageResponse]
    unread_count: int = 0


# ── Extended Profile Schemas ──────────────────────────────────────────────────


class ProfileUpdate(BaseModel):
    """Extended profile update including all demographics."""

    full_name: str | None = Field(None, min_length=1, max_length=255)
    phone: str | None = Field(None, max_length=20)
    date_of_birth: str | None = None  # ISO date string
    gender: str | None = Field(None, description="male, female, prefer_not_to_say")
    nationality: str | None = Field(None, max_length=50)
    cpr_number: str | None = Field(None, max_length=9)
    blood_type: str | None = Field(None, description="A+, A-, B+, B-, AB+, AB-, O+, O-")
    language_preference: str | None = Field(None, description="en, ar")
    timezone: str | None = Field(None, max_length=50)
    email_notifications: bool | None = None
    reddit_username: str | None = Field(None, max_length=50)
    twitter_username: str | None = Field(None, max_length=50)
    onboarding_completed: bool | None = None
    new_password: str | None = Field(None, min_length=8, max_length=128)


class OnboardingProgress(BaseModel):
    """Track which onboarding steps are complete."""

    demographics_complete: bool = False
    contact_complete: bool = False
    medical_history_complete: bool = False
    medications_complete: bool = False
    allergies_complete: bool = False
    emergency_contacts_complete: bool = False
    consent_accepted: bool = False
