"""reconcile deployed schema with current models (initial baseline)

Revision ID: 72deba99af9e
Revises:
Create Date: 2026-04-15 13:52:00.764298

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "72deba99af9e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
