"""add_email_delivery_export_and_fk_cascades

Revision ID: f48697a7f1f5
Revises: 5c08683ca181
Create Date: 2026-04-25 16:24:25.043933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48697a7f1f5'
down_revision: Union[str, Sequence[str], None] = '5c08683ca181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('allergies_patient_id_fkey'), 'allergies', type_='foreignkey')
    op.create_foreign_key(None, 'allergies', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_clinician_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['clinician_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('audit_log_user_id_fkey'), 'audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'audit_log', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('care_plans_clinician_id_fkey'), 'care_plans', type_='foreignkey')
    op.drop_constraint(op.f('care_plans_patient_id_fkey'), 'care_plans', type_='foreignkey')
    op.create_foreign_key(None, 'care_plans', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'care_plans', 'users', ['clinician_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_messages_screening_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_conversation_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'screenings', ['screening_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.drop_constraint(op.f('conversations_linked_clinician_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['linked_clinician_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('diagnoses_patient_id_fkey'), 'diagnoses', type_='foreignkey')
    op.create_foreign_key(None, 'diagnoses', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('email_deliveries_user_id_fkey'), 'email_deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'email_deliveries', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('emergency_contacts_patient_id_fkey'), 'emergency_contacts', type_='foreignkey')
    op.create_foreign_key(None, 'emergency_contacts', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_kc_category'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_kc_embedding_hnsw'), table_name='knowledge_chunks', postgresql_with={'m': '24', 'ef_construction': '200'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_kc_fts'), table_name='knowledge_chunks', postgresql_using='gin')
    op.drop_constraint(op.f('fk_kc_parent'), 'knowledge_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_chunks', 'knowledge_chunks', ['parent_chunk_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_medications_is_active'), table_name='medications')
    op.drop_constraint(op.f('medications_patient_id_fkey'), 'medications', type_='foreignkey')
    op.create_foreign_key(None, 'medications', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_user_read'), table_name='notifications')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('patient_documents_uploaded_by_fkey'), 'patient_documents', type_='foreignkey')
    op.drop_constraint(op.f('patient_documents_patient_id_fkey'), 'patient_documents', type_='foreignkey')
    op.create_foreign_key(None, 'patient_documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'patient_documents', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_prc_embedding_hnsw'), table_name='patient_rag_chunks', postgresql_with={'m': '24', 'ef_construction': '200'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_prc_fts'), table_name='patient_rag_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_prc_patient_current'), table_name='patient_rag_chunks', postgresql_where='(is_current = true)')
    op.drop_index(op.f('ix_prc_source'), table_name='patient_rag_chunks')
    op.drop_constraint(op.f('patient_rag_chunks_patient_id_fkey'), 'patient_rag_chunks', type_='foreignkey')
    op.drop_constraint(op.f('fk_prc_parent'), 'patient_rag_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'patient_rag_chunks', 'patient_rag_chunks', ['parent_chunk_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'patient_rag_chunks', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('screening_schedules_patient_id_fkey'), 'screening_schedules', type_='foreignkey')
    op.drop_constraint(op.f('screening_schedules_assigned_by_fkey'), 'screening_schedules', type_='foreignkey')
    op.create_foreign_key(None, 'screening_schedules', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'screening_schedules', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('screenings_patient_id_fkey'), 'screenings', type_='foreignkey')
    op.drop_constraint(op.f('screenings_reviewed_by_fkey'), 'screenings', type_='foreignkey')
    op.drop_constraint(op.f('screenings_care_plan_id_fkey'), 'screenings', type_='foreignkey')
    op.create_foreign_key(None, 'screenings', 'care_plans', ['care_plan_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'screenings', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'screenings', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('users_clinician_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['clinician_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_clinician_id_fkey'), 'users', 'users', ['clinician_id'], ['id'])
    op.drop_constraint(None, 'screenings', type_='foreignkey')
    op.drop_constraint(None, 'screenings', type_='foreignkey')
    op.drop_constraint(None, 'screenings', type_='foreignkey')
    op.create_foreign_key(op.f('screenings_care_plan_id_fkey'), 'screenings', 'care_plans', ['care_plan_id'], ['id'])
    op.create_foreign_key(op.f('screenings_reviewed_by_fkey'), 'screenings', 'users', ['reviewed_by'], ['id'])
    op.create_foreign_key(op.f('screenings_patient_id_fkey'), 'screenings', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'screening_schedules', type_='foreignkey')
    op.drop_constraint(None, 'screening_schedules', type_='foreignkey')
    op.create_foreign_key(op.f('screening_schedules_assigned_by_fkey'), 'screening_schedules', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(op.f('screening_schedules_patient_id_fkey'), 'screening_schedules', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'patient_rag_chunks', type_='foreignkey')
    op.drop_constraint(None, 'patient_rag_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_prc_parent'), 'patient_rag_chunks', 'patient_rag_chunks', ['parent_chunk_id'], ['id'])
    op.create_foreign_key(op.f('patient_rag_chunks_patient_id_fkey'), 'patient_rag_chunks', 'users', ['patient_id'], ['id'])
    op.create_index(op.f('ix_prc_source'), 'patient_rag_chunks', ['source_table', 'source_row_id'], unique=False)
    op.create_index(op.f('ix_prc_patient_current'), 'patient_rag_chunks', ['patient_id', 'is_current'], unique=False, postgresql_where='(is_current = true)')
    op.create_index(op.f('ix_prc_fts'), 'patient_rag_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_prc_embedding_hnsw'), 'patient_rag_chunks', ['embedding'], unique=False, postgresql_with={'m': '24', 'ef_construction': '200'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.drop_constraint(None, 'patient_documents', type_='foreignkey')
    op.create_foreign_key(op.f('patient_documents_patient_id_fkey'), 'patient_documents', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('patient_documents_uploaded_by_fkey'), 'patient_documents', 'users', ['uploaded_by'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_notifications_user_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.create_foreign_key(op.f('medications_patient_id_fkey'), 'medications', 'users', ['patient_id'], ['id'])
    op.create_index(op.f('ix_medications_is_active'), 'medications', ['is_active'], unique=False)
    op.drop_constraint(None, 'knowledge_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_kc_parent'), 'knowledge_chunks', 'knowledge_chunks', ['parent_chunk_id'], ['id'])
    op.create_index(op.f('ix_kc_fts'), 'knowledge_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_kc_embedding_hnsw'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_with={'m': '24', 'ef_construction': '200'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_kc_category'), 'knowledge_chunks', ['category', 'subcategory'], unique=False)
    op.drop_constraint(None, 'emergency_contacts', type_='foreignkey')
    op.create_foreign_key(op.f('emergency_contacts_patient_id_fkey'), 'emergency_contacts', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'email_deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('email_deliveries_user_id_fkey'), 'email_deliveries', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'diagnoses', type_='foreignkey')
    op.create_foreign_key(op.f('diagnoses_patient_id_fkey'), 'diagnoses', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_linked_clinician_id_fkey'), 'conversations', 'users', ['linked_clinician_id'], ['id'])
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_conversation_id_fkey'), 'chat_messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_screening_id_fkey'), 'chat_messages', 'screenings', ['screening_id'], ['id'])
    op.drop_constraint(None, 'care_plans', type_='foreignkey')
    op.drop_constraint(None, 'care_plans', type_='foreignkey')
    op.create_foreign_key(op.f('care_plans_patient_id_fkey'), 'care_plans', 'users', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('care_plans_clinician_id_fkey'), 'care_plans', 'users', ['clinician_id'], ['id'])
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('audit_log_user_id_fkey'), 'audit_log', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_clinician_id_fkey'), 'appointments', 'users', ['clinician_id'], ['id'])
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'allergies', type_='foreignkey')
    op.create_foreign_key(op.f('allergies_patient_id_fkey'), 'allergies', 'users', ['patient_id'], ['id'])
    # ### end Alembic commands ###
